kernel/GNUmakefile: fix cargo invocation
With the previous command, there would be a lot of errors like these:

error[E0463]: can't find crate for `core`
  |
  = note: the `x86_64-unknown-none` target may not be installed
  = help: consider downloading the target with `rustup target add x86_64-unknown-none`
  = help: consider building the standard library from source with `cargo build -Zbuild-std`

error[E0463]: can't find crate for `compiler_builtins`

At least -Z build-std=core,compiler_builtins is necessary to make this build. But for kernels, a few more options have been added, just to be sure.